export const bankData = {
  barclays: {
    name: 'Barclays',
    slug: 'barclays-bank-statement-analyser',
    h1: 'Analyse Your Barclays Bank Statement Instantly',
    intro: 'Barclays PDF statements include full transaction histories, direct debits, and standing orders across personal and business accounts. MoneySorted reads your Barclays PDF and turns it into a clean spending dashboard in seconds — no Barclays login required, no third-party access granted.',
    ctaLabel: 'Analyse My Barclays Statement Free →',
    metaTitle: 'Barclays Bank Statement Analyser | MoneySorted',
    metaDescription: 'Upload your Barclays bank statement PDF and instantly see a full spending breakdown by category, merchant and month. Free, private, no bank login required.',
    pdfNotes: [
      'Supports Barclays personal current account and business account statements',
      'Reads all PDF formats exported from Barclays Online Banking and the Barclays app',
      'Handles multi-page statements with hundreds of transactions automatically',
    ],
  },
  hsbc: {
    name: 'HSBC',
    slug: 'hsbc-bank-statement-analyser',
    h1: 'Analyse Your HSBC Bank Statement Instantly',
    intro: 'HSBC statements cover current accounts, savings, and credit cards across personal and Premier accounts. MoneySorted extracts every transaction from your HSBC PDF and categorises them automatically — groceries, bills, subscriptions, and more — so you can see exactly where your money went.',
    ctaLabel: 'Analyse My HSBC Statement Free →',
    metaTitle: 'HSBC Bank Statement Analyser | MoneySorted',
    metaDescription: 'Upload your HSBC bank statement PDF and instantly get a spending breakdown by category and merchant. Free, private, no HSBC login required.',
    pdfNotes: [
      'Supports HSBC personal, HSBC Advance, and HSBC Premier current account statements',
      'Works with statements exported from HSBC Online Banking and the HSBC UK app',
      'Correctly handles HSBC\'s multi-column transaction layout across all statement lengths',
    ],
  },
  monzo: {
    name: 'Monzo',
    slug: 'monzo-bank-statement-analyser',
    h1: 'Analyse Your Monzo Bank Statement Instantly',
    intro: "Monzo's detailed statements already tag transactions by merchant, but MoneySorted goes further — grouping your Monzo spending into categories, highlighting subscriptions, and showing monthly trends in a clean dashboard you can export to Excel or CSV.",
    ctaLabel: 'Analyse My Monzo Statement Free →',
    metaTitle: 'Monzo Bank Statement Analyser | MoneySorted',
    metaDescription: 'Upload your Monzo bank statement PDF and instantly see spending by category, top merchants and monthly trends. Free, private, no bank login required.',
    pdfNotes: [
      'Supports Monzo personal, Monzo Plus, and Monzo Premium account statements',
      'Works with PDFs exported directly from the Monzo app\'s statement download feature',
      'Preserves Monzo\'s merchant names and notes for accurate categorisation',
    ],
  },
  starling: {
    name: 'Starling',
    slug: 'starling-bank-statement-analyser',
    h1: 'Analyse Your Starling Bank Statement Instantly',
    intro: 'Starling Bank produces clean, well-structured PDF statements. MoneySorted reads your Starling statement and delivers a full spending breakdown by category, a list of your top merchants, and monthly income vs outgoing comparisons — ready to export to Excel or CSV in one click.',
    ctaLabel: 'Analyse My Starling Statement Free →',
    metaTitle: 'Starling Bank Statement Analyser | MoneySorted',
    metaDescription: 'Upload your Starling Bank statement PDF and instantly get a full spending breakdown. Free, private, works with personal, joint and business accounts.',
    pdfNotes: [
      'Supports Starling personal, joint, and business account statements',
      'Works with PDFs downloaded from the Starling app or Starling Online Banking',
      'Accurately reads Starling\'s transaction reference format and merchant display names',
    ],
  },
  lloyds: {
    name: 'Lloyds',
    slug: 'lloyds-bank-statement-analyser',
    h1: 'Analyse Your Lloyds Bank Statement Instantly',
    intro: 'Lloyds Bank statements are used by millions of UK customers for mortgage applications, visa applications, and personal budgeting. MoneySorted reads your Lloyds PDF instantly, categorises every transaction, and produces a clean Excel report — no manual data entry, no Lloyds login required.',
    ctaLabel: 'Analyse My Lloyds Statement Free →',
    metaTitle: 'Lloyds Bank Statement Analyser | MoneySorted',
    metaDescription: 'Upload your Lloyds bank statement PDF and instantly see spending by category and merchant. Free to use, private, no bank login required.',
    pdfNotes: [
      'Supports Lloyds current account, Club Lloyds, and basic account statements',
      'Works with statements exported from Lloyds Online Banking and the Lloyds Bank app',
      'Handles Lloyds\' statement pagination and running balance columns automatically',
    ],
  },
  natwest: {
    name: 'NatWest',
    slug: 'natwest-bank-statement-analyser',
    h1: 'Analyse Your NatWest Bank Statement Instantly',
    intro: 'NatWest statements are commonly needed for rental applications, mortgage checks, and expense tracking. MoneySorted parses your NatWest PDF in seconds and gives you a full breakdown by spending category, merchant, and month — without needing to log in to NatWest or share any credentials.',
    ctaLabel: 'Analyse My NatWest Statement Free →',
    metaTitle: 'NatWest Bank Statement Analyser | MoneySorted',
    metaDescription: 'Upload your NatWest bank statement PDF and instantly get a spending breakdown by category, merchant and month. Free, private, no bank login required.',
    pdfNotes: [
      'Supports NatWest personal current account and Select account statements',
      'Works with PDFs downloaded from NatWest Online Banking and the NatWest app',
      'Correctly reads NatWest\'s debit/credit column layout across all statement lengths',
    ],
  },
  santander: {
    name: 'Santander',
    slug: 'santander-bank-statement-analyser',
    h1: 'Analyse Your Santander Bank Statement Instantly',
    intro: 'Santander statements are frequently requested for mortgage applications, rental agreements, and financial reviews. MoneySorted analyses your Santander PDF and produces a colour-coded spending dashboard with category totals, merchant breakdowns, and a downloadable Excel report.',
    ctaLabel: 'Analyse My Santander Statement Free →',
    metaTitle: 'Santander Bank Statement Analyser | MoneySorted',
    metaDescription: 'Upload your Santander bank statement PDF and instantly see a full spending breakdown. Free, private, works with Everyday and 1|2|3 accounts.',
    pdfNotes: [
      'Supports Santander Everyday Current Account and 1|2|3 account statements',
      'Works with PDFs exported from Santander Online Banking and the Santander UK app',
      'Handles Santander\'s date and reference format across multi-month statements',
    ],
  },
  halifax: {
    name: 'Halifax',
    slug: 'halifax-bank-statement-analyser',
    h1: 'Analyse Your Halifax Bank Statement Instantly',
    intro: "Halifax is one of the UK's most popular high street banks, and its statements are widely used for mortgage applications and financial checks. MoneySorted reads your Halifax PDF and turns it into a detailed spending breakdown — categorised, exportable, and ready in seconds.",
    ctaLabel: 'Analyse My Halifax Statement Free →',
    metaTitle: 'Halifax Bank Statement Analyser | MoneySorted',
    metaDescription: 'Upload your Halifax bank statement PDF and instantly get a spending breakdown by category and merchant. Free to use, private, no bank login required.',
    pdfNotes: [
      'Supports Halifax Current Account and Halifax Reward Account statements',
      'Works with statements downloaded from Halifax Online Banking and the Halifax app',
      'Accurately reads Halifax\'s transaction layout including direct debits and standing orders',
    ],
  },
};
